#FIXME, you want to set your own password
spring.datasource.username=spring
spring.datasource.password=!!REPLACE-ME!!
spring.datasource.url=jdbc:mysql://localhost:3306/?allowPublicKeyRetrieval=true&useSSL=false&tinyInt1isBit=false&serverTimezone=Europe/Stockholm

google.captcha.private=

spring.mail.password=

api.customization.website.url=http://localhost:8080
api.devMode=true

# Debug logging
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.use_sql_comments=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.show-sql=true
logging.level.org.springframework.security=DEBUG

## Can be used to output SQL to file instead
#spring.jpa.properties.jakarta.persistence.schema-generation.scripts.action=create
#spring.jpa.properties.jakarta.persistence.schema-generation.scripts.create-target=create.sql
#spring.jpa.properties.jakarta.persistence.schema-generation.scripts.create-source=metadata
