/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_dfdeshom_math_GMP */

#ifndef _Included_org_dfdeshom_math_GMP
#define _Included_org_dfdeshom_math_GMP
#ifdef __cplusplus
extern "C" {
#endif
#undef org_dfdeshom_math_GMP_serialVersionUID
#define org_dfdeshom_math_GMP_serialVersionUID -8742448824652078965LL
#undef org_dfdeshom_math_GMP_serialVersionUID
#define org_dfdeshom_math_GMP_serialVersionUID -8287574255936472291LL
/*
 * Class:     org_dfdeshom_math_GMP
 * Method:    natInitializeLibrary
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_dfdeshom_math_GMP_natInitializeLibrary
  (JNIEnv *, jclass);

/*
 * Class:     org_dfdeshom_math_GMP
 * Method:    natInitialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_dfdeshom_math_GMP_natInitialize
  (JNIEnv *, jobject);

/*
 * Class:     org_dfdeshom_math_GMP
 * Method:    natFinalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_dfdeshom_math_GMP_natFinalize
  (JNIEnv *, jobject);

/*
 * Class:     org_dfdeshom_math_GMP
 * Method:    natFromLong
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_dfdeshom_math_GMP_natFromLong
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_dfdeshom_math_GMP
 * Method:    natFromBI
 * Signature: (Lorg/dfdeshom/math/Pointer;)V
 */
JNIEXPORT void JNICALL Java_org_dfdeshom_math_GMP_natFromBI
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_dfdeshom_math_GMP
 * Method:    natFromByteArray
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_org_dfdeshom_math_GMP_natFromByteArray
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     org_dfdeshom_math_GMP
 * Method:    natFromString
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_org_dfdeshom_math_GMP_natFromString
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     org_dfdeshom_math_GMP
 * Method:    natFromSignedMagnitude
 * Signature: ([BZ)V
 */
JNIEXPORT void JNICALL Java_org_dfdeshom_math_GMP_natFromSignedMagnitude
  (JNIEnv *, jobject, jbyteArray, jboolean);

/*
 * Class:     org_dfdeshom_math_GMP
 * Method:    natToString
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_dfdeshom_math_GMP_natToString
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_dfdeshom_math_GMP
 * Method:    natToByteArray
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_org_dfdeshom_math_GMP_natToByteArray
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     org_dfdeshom_math_GMP
 * Method:    natAbsIntValue
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_dfdeshom_math_GMP_natAbsIntValue
  (JNIEnv *, jobject);

/*
 * Class:     org_dfdeshom_math_GMP
 * Method:    natDoubleValue
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_org_dfdeshom_math_GMP_natDoubleValue
  (JNIEnv *, jobject);

/*
 * Class:     org_dfdeshom_math_GMP
 * Method:    natCompare
 * Signature: (Lorg/dfdeshom/math/Pointer;)I
 */
JNIEXPORT jint JNICALL Java_org_dfdeshom_math_GMP_natCompare
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_dfdeshom_math_GMP
 * Method:    natAdd
 * Signature: (Lorg/dfdeshom/math/Pointer;Lorg/dfdeshom/math/Pointer;)V
 */
JNIEXPORT void JNICALL Java_org_dfdeshom_math_GMP_natAdd
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     org_dfdeshom_math_GMP
 * Method:    natSubtract
 * Signature: (Lorg/dfdeshom/math/Pointer;Lorg/dfdeshom/math/Pointer;)V
 */
JNIEXPORT void JNICALL Java_org_dfdeshom_math_GMP_natSubtract
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     org_dfdeshom_math_GMP
 * Method:    natMultiply
 * Signature: (Lorg/dfdeshom/math/Pointer;Lorg/dfdeshom/math/Pointer;)V
 */
JNIEXPORT void JNICALL Java_org_dfdeshom_math_GMP_natMultiply
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     org_dfdeshom_math_GMP
 * Method:    natQuotient
 * Signature: (Lorg/dfdeshom/math/Pointer;Lorg/dfdeshom/math/Pointer;)V
 */
JNIEXPORT void JNICALL Java_org_dfdeshom_math_GMP_natQuotient
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     org_dfdeshom_math_GMP
 * Method:    natRemainder
 * Signature: (Lorg/dfdeshom/math/Pointer;Lorg/dfdeshom/math/Pointer;)V
 */
JNIEXPORT void JNICALL Java_org_dfdeshom_math_GMP_natRemainder
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     org_dfdeshom_math_GMP
 * Method:    natQuotientAndRemainder
 * Signature: (Lorg/dfdeshom/math/Pointer;Lorg/dfdeshom/math/Pointer;Lorg/dfdeshom/math/Pointer;)V
 */
JNIEXPORT void JNICALL Java_org_dfdeshom_math_GMP_natQuotientAndRemainder
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     org_dfdeshom_math_GMP
 * Method:    natModulo
 * Signature: (Lorg/dfdeshom/math/Pointer;Lorg/dfdeshom/math/Pointer;)V
 */
JNIEXPORT void JNICALL Java_org_dfdeshom_math_GMP_natModulo
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     org_dfdeshom_math_GMP
 * Method:    natPow
 * Signature: (ILorg/dfdeshom/math/Pointer;)V
 */
JNIEXPORT void JNICALL Java_org_dfdeshom_math_GMP_natPow
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     org_dfdeshom_math_GMP
 * Method:    natModPow
 * Signature: (Lorg/dfdeshom/math/Pointer;Lorg/dfdeshom/math/Pointer;Lorg/dfdeshom/math/Pointer;)V
 */
JNIEXPORT void JNICALL Java_org_dfdeshom_math_GMP_natModPow
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     org_dfdeshom_math_GMP
 * Method:    natModInverse
 * Signature: (Lorg/dfdeshom/math/Pointer;Lorg/dfdeshom/math/Pointer;)V
 */
JNIEXPORT void JNICALL Java_org_dfdeshom_math_GMP_natModInverse
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     org_dfdeshom_math_GMP
 * Method:    natGCD
 * Signature: (Lorg/dfdeshom/math/Pointer;Lorg/dfdeshom/math/Pointer;)V
 */
JNIEXPORT void JNICALL Java_org_dfdeshom_math_GMP_natGCD
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     org_dfdeshom_math_GMP
 * Method:    natTestPrimality
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_dfdeshom_math_GMP_natTestPrimality
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_dfdeshom_math_GMP
 * Method:    natShiftLeft
 * Signature: (ILorg/dfdeshom/math/Pointer;)V
 */
JNIEXPORT void JNICALL Java_org_dfdeshom_math_GMP_natShiftLeft
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     org_dfdeshom_math_GMP
 * Method:    natShiftRight
 * Signature: (ILorg/dfdeshom/math/Pointer;)V
 */
JNIEXPORT void JNICALL Java_org_dfdeshom_math_GMP_natShiftRight
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     org_dfdeshom_math_GMP
 * Method:    natLowestSetBit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_dfdeshom_math_GMP_natLowestSetBit
  (JNIEnv *, jobject);

/*
 * Class:     org_dfdeshom_math_GMP
 * Method:    natAbs
 * Signature: (Lorg/dfdeshom/math/Pointer;)V
 */
JNIEXPORT void JNICALL Java_org_dfdeshom_math_GMP_natAbs
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_dfdeshom_math_GMP
 * Method:    natNegate
 * Signature: (Lorg/dfdeshom/math/Pointer;)V
 */
JNIEXPORT void JNICALL Java_org_dfdeshom_math_GMP_natNegate
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_dfdeshom_math_GMP
 * Method:    natBitLength
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_dfdeshom_math_GMP_natBitLength
  (JNIEnv *, jobject);

/*
 * Class:     org_dfdeshom_math_GMP
 * Method:    natSetBitCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_dfdeshom_math_GMP_natSetBitCount
  (JNIEnv *, jobject);

/*
 * Class:     org_dfdeshom_math_GMP
 * Method:    natXor
 * Signature: (Lorg/dfdeshom/math/Pointer;Lorg/dfdeshom/math/Pointer;)V
 */
JNIEXPORT void JNICALL Java_org_dfdeshom_math_GMP_natXor
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     org_dfdeshom_math_GMP
 * Method:    natOr
 * Signature: (Lorg/dfdeshom/math/Pointer;Lorg/dfdeshom/math/Pointer;)V
 */
JNIEXPORT void JNICALL Java_org_dfdeshom_math_GMP_natOr
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     org_dfdeshom_math_GMP
 * Method:    natAnd
 * Signature: (Lorg/dfdeshom/math/Pointer;Lorg/dfdeshom/math/Pointer;)V
 */
JNIEXPORT void JNICALL Java_org_dfdeshom_math_GMP_natAnd
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     org_dfdeshom_math_GMP
 * Method:    natAndNot
 * Signature: (Lorg/dfdeshom/math/Pointer;Lorg/dfdeshom/math/Pointer;)V
 */
JNIEXPORT void JNICALL Java_org_dfdeshom_math_GMP_natAndNot
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     org_dfdeshom_math_GMP
 * Method:    natFlipBit
 * Signature: (ILorg/dfdeshom/math/Pointer;)V
 */
JNIEXPORT void JNICALL Java_org_dfdeshom_math_GMP_natFlipBit
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     org_dfdeshom_math_GMP
 * Method:    natTestBit
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_dfdeshom_math_GMP_natTestBit
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_dfdeshom_math_GMP
 * Method:    natSetBit
 * Signature: (IZLorg/dfdeshom/math/Pointer;)V
 */
JNIEXPORT void JNICALL Java_org_dfdeshom_math_GMP_natSetBit
  (JNIEnv *, jobject, jint, jboolean, jobject);

/*
 * Class:     org_dfdeshom_math_GMP
 * Method:    natNot
 * Signature: (Lorg/dfdeshom/math/Pointer;)V
 */
JNIEXPORT void JNICALL Java_org_dfdeshom_math_GMP_natNot
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
