#  name: Deploy pipe
#  on:
#    push:
#      branches: [ "master", "main" ]
#  jobs:
#    job_one:
#      name: "build and deploy"
#      runs-on: ubuntu-latest
#      steps:
#        - name: "build"
#          uses: appleboy/ssh-action@master
#          with:
#            host: world.of.ventures
#            username: ubuntu
#            key: ${{ secrets.VOW_GITHUB }}
#            port: 22
#            script: |
#              cd ~/.github
#              cd Website-API
#              git pull
#              echo "spring.profiles.active=prod" > src/main/resources/application.properties
#              ( sudo rm ~/.github/Website-API/build/libs/API-plain.war || true )
#              echo "Celebration!!!"
#              sudo bash gradlew clean build
#        - name: "deploy"
#          uses: appleboy/ssh-action@master
#          with:
#            host: world.of.ventures
#            username: ubuntu
#            key: ${{ secrets.VOW_GITHUB }}
#            port: 22
#            script: |
#              export tomcatApps="/var/lib/tomcat9/webapps"
#              ( sudo rm -rf $tomcatApps/API/ || true )
#              ( sudo rm -rf $tomcatApps/ROOT/ || true )
#              ( sudo rm $tomcatApps/API.war || true )
#              sudo service tomcat9 restart
#              sudo cp ~/.github/Website-API/build/libs/API-plain.war $tomcatApps/API.war